'use client';
import { useEffect, useState, useRef } from 'react';
import { LayoutDashboard, CheckSquare, FolderKanban, CalendarDays, Sparkles, Plug, Settings, Search, Plus, ArrowUpRight, Check, Clock3, List, Columns3, SlidersHorizontal, ChevronRight, ArrowRight, ListChecks, HardDrive, X, Clipboard, Zap, Grid2X2 } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { taskSchema, storeSchema, seed, blankTask, statuses, priorities, dateKey, dayAfter, applyProposal, type Task, type Store } from '@/lib/taskline';
import { BoardColumn, TaskList, TaskEditor, Calendar, AIConversation, SettingsPanel } from '@/components/taskline';
import { Button, STORAGE } from '@/components/taskline-shared';
import { Navigation, Topbar, WelcomeBanner } from '@/components/dashboard-chrome';

import { Integrations } from '@/components/taskline-integrations';
import { getConfig, signIn, finishSignIn, signOut, readRemote, saveRemote, livePlan, type ConnectionConfig } from '@/lib/connection';

const tones=['todo','progress','review','done'];
export default function Home(){
 const [connection,setConnection]=useState<ConnectionConfig|null>(null),[connected,setConnected]=useState(false),[connectionBusy,setConnectionBusy]=useState(false),[connectionError,setConnectionError]=useState(''),[saving,setSaving]=useState(false);
 const revision=useRef(0), pending=useRef(false), retry=useRef<{body:string;id:string}|null>(null);
 async function checkConnection(){try{const config=await getConfig();setConnection(config);setConnectionError('');const params=new URLSearchParams(window.location.search);if(params.has('state')&&(params.has('code')||params.has('error'))){setPage('Settings');setSettingsTab('integrations');try{const result=await finishSignIn(config);revision.current=result.revision;setData(result.store);setConnected(true);setUndo(null);setToast('Signed in to your shared workspace');}catch(e){setConnectionError((e as Error).message)}}}catch(e){setConnection(null);setConnectionError((e as Error).message)}}
 useEffect(()=>{void checkConnection()},[]);
 const [data,setData]=useState<Store|null>(null),[error,setError]=useState(''),[storageBlocked,setStorageBlocked]=useState(false);
 const [page,setPage]=useState('Dashboard'),[query,setQuery]=useState(''),[project,setProject]=useState('All projects'),[priority,setPriority]=useState('All priorities'),[status,setStatus]=useState('All statuses'),[due,setDue]=useState('Any date'),[sort,setSort]=useState('Due date'),[filters,setFilters]=useState(false),[view,setView]=useState('board');
 const [settingsTab,setSettingsTab]=useState('preferences'),[mobileStatus,setMobileStatus]=useState<Task['status']>('To Do');
 const [draft,setDraft]=useState<Task|null>(null),[aiOpen,setAiOpen]=useState(false),[toast,setToast]=useState(''),[undo,setUndo]=useState<Store|null>(null),[deleteId,setDeleteId]=useState<string|null>(null);
 useEffect(()=>{if(window.matchMedia('(max-width: 767px)').matches)setView('list');try{const raw=localStorage.getItem(STORAGE);const initial=raw?storeSchema.parse(JSON.parse(raw)):seed();setData(initial);if(!raw)localStorage.setItem(STORAGE,JSON.stringify(initial));}catch{setStorageBlocked(true);setData({version:1,name:'Kent',tasks:[],applied:[]});setError('Local data could not be loaded. Your stored data has not been overwritten. Check Settings to export a backup.');}},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(t)},[toast]);
 async function commit(next:Store,message:string,withUndo=false){
  if(pending.current){setError('A save is still in progress. Please wait.');return false}
  pending.current=true;setSaving(true);
  try{
   if(storageBlocked&&!connected)throw new Error('Storage is unavailable. Resolve this in Settings before making changes.');
   const checked=storeSchema.parse(next);
   if(connected){const body=JSON.stringify({revision:revision.current,store:checked});if(retry.current?.body!==body)retry.current={body,id:crypto.randomUUID()};const saved=await saveRemote(checked,revision.current,retry.current.id);revision.current=saved.revision;retry.current=null;}
   else localStorage.setItem(STORAGE,JSON.stringify(checked));
   if(withUndo)setUndo(data);else setUndo(null);setData(checked);setError('');setToast(message);return true;
  }catch(e){setError(e instanceof Error?e.message:'Could not save your changes.');return false}
  finally{pending.current=false;setSaving(false)}
 }
 async function connect(){if(!connection)return;setConnectionBusy(true);try{const result=await signIn(connection);revision.current=result.revision;setData(result.store);setConnected(true);setUndo(null);setDraft(null);setAiOpen(false);setConnectionError('');setToast('Connected to your shared workspace. Browser tasks are kept separately.');}catch(e){setConnectionError((e as Error).message)}finally{setConnectionBusy(false)}}
 async function refreshShared(){if(pending.current)return;pending.current=true;setConnectionBusy(true);try{const result=await readRemote();revision.current=result.revision;setData(result.store);setUndo(null);setConnectionError('');setToast('Shared board refreshed. Open task input has been kept.');}catch(e){setConnectionError((e as Error).message)}finally{setConnectionBusy(false)}}
 async function importBrowser(){try{const raw=localStorage.getItem(STORAGE);if(!raw)throw new Error('No browser tasks to import.');const local=storeSchema.parse(JSON.parse(raw));const known=new Set(data!.tasks.map(t=>t.id));const extra=local.tasks.filter(t=>!known.has(t.id));if(await commit({...data!,tasks:[...data!.tasks,...extra]},`Imported ${extra.length} browser tasks`,true))setConnectionError('');}catch(e){setConnectionError((e as Error).message)}}
 async function disconnect(){setConnectionBusy(true);try{await signOut()}catch(e){setConnectionError((e as Error).message);setConnectionBusy(false)}}

 if(!data)return <div className="loading"><img src="/favicon.svg" alt="" width="48" height="48"/><h1>Opening your workspace…</h1></div>;
 const projects=Array.from(new Set(data.tasks.map(t=>t.project))).sort();
 function resetFilters(){setQuery('');setProject('All projects');setPriority('All priorities');setStatus('All statuses');setDue('Any date');}
 function go(s:string,p?:string){setPage(s==='Integrations'?'Settings':s);setSettingsTab(s==='Integrations'?'integrations':'preferences');resetFilters();if(p)setProject(p);if(s==='My Tasks')setView('list');if(s==='Dashboard')setView(window.matchMedia('(max-width:767px)').matches?'list':'board');}
 function chooseStatus(s:string){setStatus(s);if(s==='Completed')setView('list');else if(statuses.includes(s as Task['status']))setMobileStatus(s as Task['status']);}
 function quickFilter(label:string){resetFilters();if(label==='Completed'){setStatus('Completed');setView('list');}else if(label!=='All active')setDue(label);}
 function move(t:Task,s:Task['status']){commit({...data!,tasks:data!.tasks.map(x=>x.id===t.id?{...x,status:s}:x)},`Moved to ${s}`,true)}
 async function saveTask(t:Task){try{const parsed=taskSchema.parse(t);const exists=data!.tasks.some(x=>x.id===t.id);if(await commit({...data!,tasks:exists?data!.tasks.map(x=>x.id===t.id?parsed:x):[...data!.tasks,parsed]},exists?'Task updated':'Task created',true))setDraft(null)}catch{setError('Please enter a title and project, and check the task details.')}}
 const visible=data.tasks.filter(t=>(project==='All projects'||t.project===project)&&(priority==='All priorities'||t.priority===priority)&&(status==='All statuses'?t.status!=='Completed':t.status===status)&&(!query||`${t.title} ${t.description} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(due==='Any date'||(due==='Today'?t.due===dateKey():due==='Overdue'?!!t.due&&t.due<dateKey()&&t.status!=='Completed':due==='No date'?!t.due:!!t.due&&t.due>dateKey()&&t.due<=dayAfter(7)))).sort((a,b)=>sort==='Priority'?priorities.indexOf(a.priority)-priorities.indexOf(b.priority):sort==='Title'?a.title.localeCompare(b.title):(a.due||'9999').localeCompare(b.due||'9999'));
 const complete=data.tasks.filter(t=>t.status==='Completed').length;
 const activeQuick=status==='Completed'?'Completed':due==='Any date'?'All active':due;
 const hasFilters=!!query||project!=='All projects'||priority!=='All priorities'||status!=='All statuses'||due!=='Any date';
 const controls=filters?<div className="filter-panel"><label>Project<select aria-label="Filter by project" value={project} onChange={e=>setProject(e.target.value)}><option>All projects</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label>Priority<select aria-label="Filter priority" value={priority} onChange={e=>setPriority(e.target.value)}><option>All priorities</option>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Status<select aria-label="Filter status" value={status} onChange={e=>chooseStatus(e.target.value)}><option>All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort by<select aria-label="Sort tasks" value={sort} onChange={e=>setSort(e.target.value)}>{['Due date','Priority','Title'].map(s=><option key={s}>{s}</option>)}</select></label><Button onClick={resetFilters}>Reset filters</Button></div>:null;
 const filterSummary=hasFilters?<div className="active-filter-summary" aria-live="polite"><span>Showing {visible.length} {visible.length===1?'task':'tasks'}</span>{[query&&`Search: ${query}`,project!=='All projects'&&project,priority!=='All priorities'&&priority,status!=='All statuses'&&status,due!=='Any date'&&due].filter(Boolean).map((f,i)=><span className="filter-chip" key={i}>{f}</span>)}<button onClick={resetFilters}>Reset <X size={13}/></button></div>:null;
 const actionRow=<div className="dashboard-actions"><p><span className="attention-dot"/>You have <strong>{data.tasks.filter(t=>t.due===dateKey()&&t.priority==='High'&&t.status!=='Completed').length} high-priority tasks</strong> scheduled today. Keep your next step in focus.</p><div className="heading-actions"><Button onClick={()=>setAiOpen(true)}><Sparkles size={16}/>Organize with AI</Button><Button onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={17}/>Filter{hasFilters&&<span className="filter-dot"/>}</Button><Button primary onClick={()=>newTask()}><Plus size={18}/>New Task</Button></div></div>;
 const newTask=(s:Task['status']='To Do')=>setDraft(blankTask(s,project==='All projects'?'Website Launch':project));
 const board=<section className="board-section"><Tabs value={view} onValueChange={setView}><label className="mobile-search"><Search size={17}/><input aria-label="Search tasks on mobile" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks"/></label><div className="board-toolbar"><div className="quick-filters" aria-label="Quick task filters">{['All active','Today','Upcoming','Overdue','Completed'].map(label=><button key={label} aria-pressed={activeQuick===label} onClick={()=>quickFilter(label)}>{label}</button>)}</div><div className="board-view-controls">{view==='board'&&<label className="mobile-column-picker">Column<select aria-label="Board column" value={mobileStatus} onChange={e=>setMobileStatus(e.target.value as Task['status'])}>{statuses.slice(0,3).map(s=><option key={s}>{s}</option>)}</select></label>}<TabsList><TabsTrigger value="board" disabled={status==='Completed'}><Columns3/>Board</TabsTrigger><TabsTrigger value="list"><List/>List</TabsTrigger></TabsList></div></div>{controls}{filterSummary}<TabsContent value="board"><div className="board">{statuses.slice(0,3).map((s,i)=><BoardColumn key={s} status={s} tone={tones[i]} mobileActive={s===mobileStatus} tasks={visible.filter(t=>t.status===s)} allTasks={data.tasks} open={setDraft} move={move} add={()=>newTask(s)}/>)}</div></TabsContent><TabsContent value="list"><TaskList tasks={visible} open={setDraft} move={move}/></TabsContent></Tabs></section>;
 const ai=<AIConversation live={!!(connected&&connection?.aiReady)} generatePlan={prompt=>livePlan(prompt,revision.current)} tasks={data.tasks} applied={data.applied} onApply={async(p,s)=>{try{return commit(applyProposal(data,p,s),'Plan applied to your board',true)}catch(e){setError((e as Error).message);return false}}}/>;
 return <SidebarProvider style={{'--sidebar-width':'260px'} as React.CSSProperties}><Navigation page={page} go={go} projects={projects} settingsTab={settingsTab}/><div className="main-shell"><Topbar page={page} name={data.name} query={query} setQuery={q=>{if(!['Dashboard','My Tasks','Projects & Boards','Calendar'].includes(page))go('My Tasks');setQuery(q)}} blocked={storageBlocked&&!connected} syncLabel={saving?'Saving…':connected?'Shared workspace':'Saved locally'} openSettings={()=>go('Settings')}/><main className="main-content">{connected&&<div className="shared-toolbar"><span>Shared workspace · changes from ChatGPT appear after refresh</span><Button disabled={saving||connectionBusy} onClick={refreshShared}>Refresh board</Button></div>}{error&&<div className="error-banner" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
 {page==='Dashboard'?<WelcomeBanner name={data.name}/>:<div className="page-heading"><div><p className="eyebrow">Main Workspace</p><h1>{page}</h1><p>{page==='My Tasks'?'Everything on your plate, in one place.':page==='Calendar'?'Your schedule, one day at a time.':page==='Projects & Boards'?'Big ideas, broken into achievable steps.':page==='AI Assistant'?'Describe your work. Review a plan. Make it happen.':'Your workspace, preferences, and connections.'}</p></div></div>}
 {['Dashboard','My Tasks','Projects & Boards','Calendar'].includes(page)&&actionRow}
 {page==='Dashboard'&&<><div className="summary-grid">{[{label:'Total Tasks',count:data.tasks.length,icon:Clipboard,note:`Across ${projects.length} active boards`,tone:'total',status:'All statuses'},{label:'In Progress',count:data.tasks.filter(t=>t.status==='In Progress').length,icon:Zap,note:`${data.tasks.filter(t=>t.status==='In Progress').reduce((sum,t)=>sum+t.estimate,0)} estimated hours in progress`,tone:'progress',status:'In Progress'},{label:'Needs Review',count:data.tasks.filter(t=>t.status==='In Review').length,icon:Grid2X2,note:`${data.tasks.filter(t=>t.status==='In Review').length} ${data.tasks.filter(t=>t.status==='In Review').length===1?'task':'tasks'} awaiting review`,tone:'review',status:'In Review'},{label:'Completed',count:complete,icon:Check,note:'Tasks finished in this workspace',tone:'done',status:'Completed'}].map(({label,count,icon:Icon,note,tone,status:s})=><button key={label} className={'summary-card '+tone} onClick={()=>{resetFilters();chooseStatus(s);}}><div><span>{label}</span><Icon size={20}/></div><strong>{count}</strong><small>{note}</small></button>)}</div>{board}</>}
 {page==='My Tasks'&&board}
 {page==='Projects & Boards'&&<><div className="project-grid">{projects.map((p,i)=>{const ts=data.tasks.filter(t=>t.project===p),done=ts.filter(t=>t.status==='Completed').length;return <button className="project-card" key={p} onClick={()=>setProject(project===p?'All projects':p)}><span className={'project-icon project-'+i%3}><FolderKanban/></span><h2>{p}</h2><p>{ts.length} tasks · {done} completed</p><div className="progress-track"><span style={{width:`${done/ts.length*100}%`}}/></div></button>})}</div>{board}</>}
 {page==='Calendar'&&<>{controls}{filterSummary}<Calendar tasks={visible} open={setDraft}/></>}
 {page==='AI Assistant'&&<div className="assistant-page">{ai}</div>}
 {page==='Settings'&&<Tabs value={settingsTab} onValueChange={setSettingsTab} className="settings-tabs"><TabsList><TabsTrigger value="preferences">Preferences</TabsTrigger><TabsTrigger value="integrations">Integrations</TabsTrigger></TabsList><TabsContent value="preferences"><SettingsPanel data={data} save={next=>commit(next,'Settings saved')} blocked={storageBlocked&&!connected} connected={connected}/></TabsContent><TabsContent value="integrations"><Integrations config={connection} connected={connected} busy={connectionBusy||saving} error={connectionError} check={checkConnection} connect={connect} refresh={refreshShared} importLocal={importBrowser} disconnect={disconnect} openAI={()=>go('AI Assistant')}/></TabsContent></Tabs>}
 </main><footer className="page-footer">A little more organized. A little more at ease.<span>taskbloc · Personal workspace</span></footer></div>
 <Sheet open={!!draft} onOpenChange={o=>{if(!o)setDraft(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Task details</SheetTitle><SheetDescription>Edit the details, then save your changes.</SheetDescription></SheetHeader>{error&&<div className="drawer-error" role="alert">{error}</div>}{draft&&<TaskEditor key={draft.id} task={draft} tasks={data.tasks} projects={projects} onSave={saveTask} onDelete={data.tasks.some(t=>t.id===draft.id)?()=>setDeleteId(draft.id):undefined}/>}</SheetContent></Sheet>
 <Sheet open={aiOpen} onOpenChange={setAiOpen}><SheetContent className="ai-sheet"><SheetHeader><SheetTitle className="flex items-center gap-2"><Sparkles size={20}/> taskbloc assistant <span className="demo-pill">{connected&&connection?.aiReady?'Live AI':'Demo'}</span></SheetTitle><SheetDescription>A plan you can shape before anything changes.</SheetDescription></SheetHeader>{ai}</SheetContent></Sheet>
 <AlertDialog open={!!deleteId} onOpenChange={o=>{if(!o)setDeleteId(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this task?</AlertDialogTitle><AlertDialogDescription>Its checklist will also be removed. Other tasks will no longer depend on it. You can undo this change.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep task</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(await commit({...data,tasks:data.tasks.filter(t=>t.id!==deleteId).map(t=>({...t,dependencies:t.dependencies.filter(id=>id!==deleteId)}))},'Task deleted',true)){setDraft(null);setDeleteId(null)}}}>Delete task</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 {(toast||undo)&&<div className="toast" role="status"><Check size={18}/><span>{toast||'Last change saved'}</span>{undo&&<button onClick={async()=>{if(await commit(undo,'Change undone'))setUndo(null)}}>Undo</button>}<button aria-label="Dismiss notification" onClick={()=>{setToast('');setUndo(null)}}><X size={16}/></button></div>}
 </SidebarProvider>;
}



