'use client';
import { useState } from 'react';
import { Sparkles, Plug, ArrowRight, RefreshCw, Copy, LogIn } from 'lucide-react';
import { Button } from './taskline-shared';
import { type ConnectionConfig } from '@/lib/connection';

export function Integrations({config,connected,busy,error,check,connect,refresh,importLocal,disconnect,openAI}:{config:ConnectionConfig|null;connected:boolean;busy:boolean;error:string;check:()=>void;connect:()=>void;refresh:()=>void;importLocal:()=>void;disconnect:()=>void;openAI:()=>void}) {
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
 const live=connected&&config?.aiReady;
 const connectorMissing=config?.missing.filter(item=>item!=='OpenAI API key')||[];
 return <><div className="connection-toolbar"><p>{connected?'Shared personal workspace · signed in':'Browser workspace · your existing tasks remain on this device'}</p><Button disabled={busy} onClick={check}><RefreshCw size={15}/>Check connection</Button></div>{error&&<p className="drawer-error" role="alert">{error}</p>}<div className="integration-grid">
 <section className="integration-card"><Sparkles/><h2>In-app AI assistant</h2><span className="demo-pill">{config?.aiPaused?'Live AI paused':live?'Live AI configured':config?.aiReady?'Sign in to use live AI':'Demo available · live setup needed'}</span><p>{config?.aiPaused?'Live AI is paused. Use the demo assistant to preview and edit task plans without API requests.':live?'Ask OpenAI to organize your shared tasks. Review and edit the proposal before applying it to your board.':'Use the local demo now, or connect your account and server-side API key for live planning.'}</p><Button onClick={openAI}>{live?'Open AI assistant':'Open demo assistant'}<ArrowRight size={16}/></Button><details><summary>Live assistant setup</summary><p>Run <code>npm run backend</code>. When ready to enable live planning, set <code>TASKLINE_AI_ENABLED=true</code> on the backend and restart it. Configure the OpenAI API key securely in the server’s ignored <code>.env.local</code> file. The browser never receives the key.</p><p>Live requests send your prompt and shared task context to OpenAI. API usage is billed separately from a ChatGPT subscription.</p><p>Review → edit → apply. Nothing changes until you apply a proposal; Undo stays available afterward.</p></details></section>
 <section className="integration-card"><Plug/><h2>External ChatGPT connector</h2><span className={connected?'demo-pill':'neutral-pill'}>{config?.browserOnly?'Shared connection not enabled':connected?'Shared backend connected':config?.authReady?'Ready to sign in':'MCP implemented · setup required'}</span><p>{config?.browserOnly?'This version saves tasks in this browser. Shared tasks and ChatGPT will be available after the hosted backend is connected.':'Connect ChatGPT to the same persistent workspace to find tasks, preview changes, apply an approved plan, and undo changes.'}</p>{config?.authReady&&!connected&&<Button primary disabled={busy} onClick={connect}><LogIn size={16}/>Sign in & connect</Button>}{connected&&<div className="connection-buttons"><Button disabled={busy} onClick={refresh}><RefreshCw size={15}/>Refresh shared board</Button><Button disabled={busy} onClick={importLocal}>Import browser tasks</Button><Button disabled={busy} onClick={connect}>Reconnect</Button><Button disabled={busy} onClick={disconnect}>Sign out</Button></div>}
 {config?.resource&&<div className="endpoint-field"><label htmlFor="mcp-url">MCP server URL</label><input id="mcp-url" value={config.resource} readOnly/><Button onClick={async()=>{try{await navigator.clipboard.writeText(config.resource);setCopied(true);setCopyError('');}catch{setCopyError('Select the URL above and copy it manually.')}}}><Copy size={14}/>{copied?'Copied':'Copy URL'}</Button>{copyError&&<p role="status">{copyError}</p>}</div>}
 <details open={!config?.authReady&&!config?.browserOnly}><summary>Connector setup</summary><ol><li>Start the backend and give it a persistent disk.</li><li>Configure an Auth0 application and API with PKCE, MCP authorization, and the scopes <code>tasks:read</code> and <code>tasks:write</code>. Add your account as an allowed workspace member.</li><li>Expose the backend over HTTPS and set its public URL, OAuth issuer, and web client ID in <code>.env.local</code>. See <code>CONNECTOR-SETUP.md</code> in the project.</li><li>Sign in here. Import your browser tasks if you want them available in ChatGPT.</li><li>Add the MCP URL to ChatGPT in developer mode, choose OAuth, and sign in with the same account.</li></ol><p className="helper">{connectorMissing.length?'Still needed: '+connectorMissing.join(', ')+'.':config?'No OpenAI API key is needed for this connector. Sign in, verify workspace access, and finish the OAuth connection in ChatGPT.':'Backend not reached yet. Start it, then select Check connection.'}</p></details>
 </section></div></>;
}
